## Linear Algebra with Scipy and NumPy

In [10]:
import numpy as np
from scipy import linalg
a=np.array([1,2])
b=np.array([2,3])
c=a*b
c

array([2, 6])

### Find inverse Matrix

In [9]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [10]:
from scipy import linalg
A_inv = linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
from scipy import linalg
import numpy as np
A = np.array([[1, 2], [3, 4]])
b_transpose = A.T
b_transpose

array([[1, 3],
       [2, 4]])

In [5]:
A*b_transpose

array([[ 1,  6],
       [ 6, 16]])

In [3]:
import numpy as np
from scipy import linalg
A = np.array([[1, 2], [3, 4]])
b_transpose = A.T
A@b_transpose

array([[ 5, 11],
       [11, 25]])

<img src="figure/linear_eq.png" >

In [11]:
A = np.array([
    [1, 3, 5],
    [2, 5, 1],
    [2, 3, 8]
])
b = np.array([10, 8, 3])

In [12]:
linalg.inv(A).dot(b)

array([-9.28,  5.16,  0.76])

In [13]:
linalg.solve(A, b)

array([-9.28,  5.16,  0.76])

### Finding the determinant

We have square matrix $A$, then its determinant is $M_{ij}=|A_{ij}|$. For the general form
\begin{equation}
    |A|=\sum_{j}(-1)^{i+j}a_{ij}M_{ij}
\end{equation}. <br>

For example, we have \begin{equation}
    A = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 5 & 1 \\ 2 & 3 & 8 \end{bmatrix}
\end{equation}

In [9]:
A = np.array([
    [1, 3, 5],
    [2, 5, 1],
    [2, 3, 8]
])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [10]:
A_det = linalg.det(A)
A_det

-25.000000000000004

### Computing Norms

<img src="figure/norm.png">

In [14]:
A = np.array([
    [1, 3, 5],
    [2, 5, 1],
    [2, 3, 8]
])

In [17]:
linalg.norm(A, 1) ## ord 1 or absolute norm

14.0

In [16]:
linalg.norm(A, 2) ## ord 2 or Euclidean norm

11.133851342531154

In [18]:
linalg.norm(A, 'fro') ## Frobenius norm by default

11.916375287812984

In [19]:
linalg.norm(A, np.inf) ## ord=inf 

13.0

### Solving for EigenValues and EigenVectors
<img src="figure/eigen1.png">

<img src="figure/eigen2.png">

In [20]:
A = np.array([
    [1, 3, 5],
    [2, 5, 1],
    [2, 3, 8]
])

In [21]:
la, v = linalg.eig(A)

In [22]:
la

array([10.5540456 +0.j, -0.5873064 +0.j,  4.03326081+0.j])

In [23]:
v

array([[-0.51686204, -0.94195144,  0.11527992],
       [-0.32845853,  0.31778071, -0.81936883],
       [-0.79054957,  0.10836468,  0.56155611]])

In [24]:
l1, l2, l3 = la

In [25]:
l1

(10.5540455960959+0j)

In [26]:
l2

(-0.5873064038673474+0j)

In [27]:
l3

(4.03326080777145+0j)

In [28]:
np.sum(abs(v**2), axis=0)

array([1., 1., 1.])

### Singular Value Decomposition
<img src="figure/svd.png">

In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [30]:
M, N = A.shape

In [31]:
U, s, Vh = linalg.svd(A)

In [32]:
U

array([[-0.14087668, -0.82471435,  0.5377697 , -0.1039411 ],
       [-0.34394629, -0.42626394, -0.63955314,  0.539418  ],
       [-0.54701591, -0.02781353, -0.33420281, -0.7670127 ],
       [-0.75008553,  0.37063688,  0.43598625,  0.3315358 ]])

In [33]:
s

array([2.54624074e+01, 1.29066168e+00, 2.31173375e-15])

In [34]:
Vh

array([[-0.50453315, -0.5745157 , -0.64449826],
       [ 0.76077568,  0.05714052, -0.64649464],
       [-0.40824829,  0.81649658, -0.40824829]])

In [35]:
Sig = linalg.diagsvd(s, M, N)

In [36]:
Sig

array([[2.54624074e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.29066168e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.31173375e-15],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [37]:
U.dot(Sig.dot(Vh))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])